// Generated by vector-scene-layout/scripts/frame_tokens.py. Do not edit by hand;
// re-run the script when a target changes.
export const tokensByTarget = {
  "custom": {
    "target": "custom",
    "width": 1200,
    "height": 600,
    "scale": 1.1111,
    "phonePreviewScale": 0.325,
    "safe": {
      "top": 30,
      "right": 60,
      "bottom": 72,
      "left": 60
    },
    "safeWidth": 1080,
    "safeHeight": 498,
    "grid": {
      "columns": 12,
      "gutter": 24,
      "column": 68.0
    },
    "type": {
      "caption": 36,
      "body": 54,
      "headline": 94,
      "display": 134
    },
    "minWeight": {
      "caption": 500,
      "body": 500,
      "headline": 600,
      "display": 700
    },
    "lineHeight": 1.15,
    "maxCharsPerLine": 20,
    "stroke": {
      "min": 4,
      "regular": 5,
      "bold": 9
    },
    "icon": {
      "sm": 68,
      "md": 94,
      "lg": 201
    },
    "radius": 18
  }
} as const;

export type TargetId = keyof typeof tokensByTarget;
export type Tokens = (typeof tokensByTarget)[TargetId];
export const tokensFor = (target: string): Tokens => {
  const t = tokensByTarget[target as TargetId];
  if (!t) throw new Error(`unknown target ${target}`);
  return t;
};

